---
# The name of the cluster.
# This value will be in your DNS entries and should conform to valid DNS characters.
cluster_name: openshift

# The OpenShift version to install.
openshift_minor: 3
openshift_major: 11
openshift_patch: 16

# IMPORTANT: Make sure this value is quoted, otherwise it gets read as 3.x instead of 3.xx release.
openshift_version: "{{ openshift_minor }}.{{ openshift_major }}"

# The base subdomain to use for your cluster.
# Example: If you set this to `example.com`, a DNS entry for `<cluster_name>.example.com` will be created).
openshift_base_domain: example.com

# Derived public DNS entry for your cluster.
openshift_public_hostname: "{{ cluster_name }}.{{ openshift_base_domain }}"
cluster_name_verbose: "{{ openshift_public_hostname | replace('.', '-') }}"
cluster_group_name: "{{ cluster_name_verbose | replace('-', '_') }}"

# The public DNS entry for bastion.
domain_name: "bastion.{{ cluster_name }}.{{ openshift_base_domain }}"

# The email address to use when generating Lets Encrypt certs for the cluster.
cert_email_address: foo@example.com

# The AWS region (i.e. `us-east-1`).
aws_region: us-east-1

# The directory that contains public key material.
keys_dir: /your/path/here

# The name of the ec2 instances public key.
ec2_key_name: "{{ cluster_name_verbose }}"

# The ec2 instances public key file.
ec2_key_file: "{{ keys_dir }}/{{ ec2_key_name }}.pem"

# The primary CIDR of the VPC.
ec2_vpc_cidr_block: 172.31.0.0/16

# EC2 default user password.
# ec2_user_pass: changeme!

# Wetty terminal in browser port.
wetty_port: 8888

# Use Let's Encrypt to generate certificate information.
use_lets_encrypt: true

# Generates a set of non-admin users that can be used for workshops,
# demos, etc. Users are created with the prefix plus a number using
# the password specified.
generic_user: changeme!
generic_pass: changeme!
generic_group: changeme!
generic_count: 3

# Default ansible configuration.
ansible_user: ec2-user
ansible_ssh_private_key_file: "{{ ec2_key_file }}"
