---

- name: Checkout devsecops-workshop repo
  git:
    repo: "https://github.com/ecwpz91/devsecops-workshop.git"
    dest: "/home/{{ ansible_user }}/devsecops-workshop"
    version: "master"
    force: yes

- name: Copy script for caching CI/CD images across nodes
  copy:
    src: "../files/cache_docker_images.yml"
    dest: "/home/{{ ansible_user }}/cache_docker_images.yml"
    mode: 0644

- name: Copy script forbatch provisioning init variables
  template:
    src: "../files/provision-batch-init.sh"
    dest: "/home/{{ ansible_user }}/devsecops-workshop/scripts/provision-batch-init.sh"
    mode: 0775

- name: Copy script for CI/CD installation
  template:
    src: "../files/install-cicd.sh"
    dest: "/home/{{ ansible_user }}/install-cicd.sh"
    mode: 0775

- name: Provide details to check CI/CD installation
  debug:
   msg: "Check file '/home/{{ ansible_user }}/install-cicd.log' on bastion 'ssh ec2-user@{{ domain_name }}' "

- name: Run CI/CD installation script
  shell: ./install-cicd.sh |& tee install-cicd.log
  args:
   chdir: "/home/{{ ansible_user }}"
